#!/bin/bash

ppa="sporkwitch/autokey"
pkgs1="autokey-gtk"
pkgs2="autokey-qt"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then

	if  [ $(_check ${pkgs1}) == "y" -o $(_check ${pkgs2}) == "y" ]   &&  [ $(_ppacheck ${ppa}) == "y" ] ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then


	if  [ $(_check ${pkgs1}) == "y" -o $(_check ${pkgs2}) == "y" ]   &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"

	else
	_ppainstall ${ppa}
	_install ${pkgs1}
	_install ${pkgs2}
	
	fi

	
# Purge
elif [ "$1" == "-p" ] ; then


	_purge ${pkgs1}
	_purge ${pkgs2}

	echo "PPAを削除します。"
	_ppapurge ${ppa}

fi
