#!/bin/bash

ppa="ubuntuhandbook1/avidemux"
pkgs="avidemux2.7-qt5 avidemux2.7-qt5-data avidemux2.7-plugins-qt5 avidemux2.7-jobs-qt5"


datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "y" ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else
	
	_install ${pkgs}
	
	fi

	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}



fi
