#!/bin/bash

ppa="dummy"
pkgs="calibre"


datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then

	if [ -d /opt/calibre ] && [ $(_check ${pkgs}) == "n" ] ; then
		echo TRUE
	else
		echo FALSE
	fi	

# Install
elif [ "$1" == "-i" ] ; then

_installcalibre()
{
	INSTDIR="/tmp"
	echo "インストーラをダウンロードします。"
	
	cd $INSTDIR
	
		
	
	if sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin ; then
		_log "インストールに成功しました。"
	else
		_err "インストールに失敗しました。"
		return 1
	fi	
	
	
	if [ -f $INSTDIR/linux-installer.sh] ; then
		rm -f $INSTDIR/linux-installer.sh
	fi	
	
}


	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else
		_installcalibre | grep -e Error -e Fatal  -e NOTE  >> /tmp/mm_pkginst.log		
	fi
	
	if [ -d /opt/calibre ] ; then
		_log "calibreのインストールに成功しました。"
	else
		_err "calibreのインストールに失敗しました。フォルダが残ったかもしれませせん。"
	fi
	
	

	
# Purge
elif [ "$1" == "-p" ] ; then


	if sudo -v && sudo calibre-uninstall ; then
		_log "calibreのアンインストールに成功しました。"
	else
		_err "calibreのアンインストールに失敗しました。フォルダが残ったかもしれませせん。"
	fi


fi
