#!/bin/bash

ppa="dummy"
pkgs="mintstick"

datadir=$(cd $(dirname "$0") && pwd)
mintstr="mint"


. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(grep -c $mintstr  /etc/apt/sources.list.d/official-package-repositories.list) -gt 0 ]  ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(grep -c $mintstr  /etc/apt/sources.list.d/official-package-repositories.list) -eq 0 ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else

	_install ${pkgs}
	
	fi

	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

fi
