#!/bin/bash

srclist="/etc/apt/sources.list.d/playonlinux.list"
pkgs="playonlinux"


datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ ! -e $srclist ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then


_installpolmo ()
{
    cd /tmp
    svn checkout https://github.com/megamuteki/misc/trunk/wine/PlayOnLinux/POL
    cd /tmp/POL

	if [ -e /usr/share/playonlinux/lang/locale/ja/LC_MESSAGES/pol.mo ] ; then
    	sudo mv /usr/share/playonlinux/lang/locale/ja/LC_MESSAGES/pol.mo  /usr/share/playonlinux/lang/locale/ja/LC_MESSAGES/pol.mo.bk
    	sudo cp pol.mo  /usr/share/playonlinux/lang/locale/ja/LC_MESSAGES/
	elif [ -e /usr/share/locale/ja/LC_MESSAGES/pol.mo ]  ; then
	    sudo mv /usr/share/locale/ja/LC_MESSAGES/pol.mo  /usr/share/locale/ja/LC_MESSAGES/pol.mo.bk
    	sudo cp pol.mo  /usr/share/locale/ja/LC_MESSAGES/pol.mo
	fi
	
}


	if [ $(_check ${pkgs}) == "y" ]  &&  [ -e $srclist ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else

	_install ${pkgs}
	_installpolmo

	fi

	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

    sudo rm -f $srclist

fi
