#!/bin/bash

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

ppa="dummy"
pkgs="rlinux"

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	echo "R-Linuxをダウンロードしています。"
	cd /tmp
	deb="RLinux5_x64.deb"
	_log "https://www.r-studio.com/downloads/RLinux5_x64.deb"
	if wget -c https://www.r-studio.com/downloads/${deb} ; then
		_log "RLinux5_x64.debのダウンロードに成功しました。"
	else
		_err "RLinux5_x64.debのダウンロードに失敗しました。"
		return 1
	fi
	
	if sudo dpkg -i ${deb} ; then
		_log "RLinux5_x64.debのインストールに成功しました。"
	else
		_err "RLinux5_x64.debのインストールに失敗しました。"
		return 1
	fi
		
	_log "一時ファイルを除去しています..."
	rm -f ${deb}

# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

fi
