#!/bin/bash

pkgs="smtube smplayer"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "n" ] ; then
		echo FALSE
	else
		echo TRUE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	_install ${pkgs}
	cp /usr/share/applications/smtube.desktop $(_desktop)/smtube.desktop
	
	if [ $(_check pulseaudio) == "n" ] ; then
		mkdir -p "${HOME}/.config/smplayer/"
		echo "[%General]
config_version=4
driver\audio_output=alsa
" > "${HOME}/.config/smplayer/smplayer.ini"
	fi
	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge "${pkgs} mplayer"
	rm -f $(_desktop)/smtube.desktop
fi
