#!/bin/bash

ppa="Dummy"
pkgs="sweethome3d  sweethome3d-furniture"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ ! -e /opt/SweetHome3D-6.2/SweetHome3D ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ -e /opt/SweetHome3D-6.2/SweetHome3D ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else

	_install ${pkgs}
	
	fi

	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}


fi
