#!/bin/bash

ppa="dummy"
pkgs=" teamviewer"
debs="https://download.teamviewer.com/download/version_12x/teamviewer_i386.deb"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check

if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then


_preinstalltiemviewer()
{
    wget -O - https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | apt-key add -
    sudo sh -c 'echo "deb http://linux.teamviewer.com/deb stable main" >> /etc/apt/sources.list.d/teamviewer.list'
    sudo apt update
}


    _preinstalltiemviewer
	cd /tmp

	if  _debinstall ${debs}; then
		_log "$pkgsインストールに成功しました。"
	else
		_err "$pkgsのインストールに失敗しました。"
	
	fi


	
# Purge
elif [ "$1" == "-p" ] ; then

_postuninstallteamviewer()
{
	#リポジトリの削除
    sudo rm  -f /etc/apt/sources.list.d/teamviewer.list
	sudo apt update

}

	_purge ${pkgs}
	_postuninstallteamviewer

fi

