#!/bin/bash

pkgs="vlc vlc-plugin-notify libavcodec-extra browser-plugin-vlc vlc-plugin-skins2 vlc-plugin-video-splitter vlc-plugin-visualization"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "n" ] ; then
		echo FALSE
	else
		echo TRUE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	_install ${pkgs}
	cp /usr/share/applications/vlc.desktop $(_desktop)/vlc.desktop
	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}
	rm -f $(_desktop)/vlc.desktop
fi
