#!/bin/bash

ppa="videolan/master-daily"

#ppa="foge"

pkgs="vlc vlc-plugin-notify libavcodec-extra browser-plugin-vlc vlc-plugin-skins2 vlc-plugin-video-splitter vlc-plugin-visualization"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then

     test=$(_ppacheck ${ppa})

     echo $test >> test.txt 

	if [ $(_check ${pkgs}) == "y" ]  && [ $(_ppacheck ${ppa}) == "y" ]  ; then
		echo TRUE

	else
		
		echo FALSE

	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	
	echo "PPAを登録します。"
	_ppainstall ${ppa}
	
	_install ${pkgs}

	
# Purge
elif [ "$1" == "-p" ] ; then

	_purge ${pkgs}


	echo "PPAを削除します。"
	_ppapurge ${ppa}


	
fi
