#!/bin/bash

ppa="dummy"
aptpkgs="code"
debpkgs="vscode.deb"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check

if [ "$1" == "-c" ] ; then
	if [ $(_check ${aptpkgs}) == "y" ]  &&  [ -e /usr/bin/code ]   ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	echo "$debpkgsをダウンロードしています。"
	cd /tmp
	

	if wget -c curl -L https://go.microsoft.com/fwlink/?LinkID=760868 -o $debpkgs ; then
		_log "$debpkgsのダウンロードに成功しました。"
	else
		_err "$debpkgsのダウンロードに失敗しました。"
	
	fi
		
	
	if sudo dpkg -i $debpkgs  ; then
		_log "$debインストールに成功しました。"
	else
		sudo apt update --fix-missing
		if sudo apt install --fix-broken ; then
			_log "$debインストールに成功しました。"
		else
			_err "$debのインストールに失敗しました。"

		fi

	fi

	_log "一時ファイルを除去しています..."

	rm -f $debpkgs


	
# Purge
elif [ "$1" == "-p" ] ; then

	_purge ${aptpkgs}


fi


