#!/bin/bash

ppa="dummy"
aptpkgs="code"
debpkgs="visual studio code"
devpkgs="software-properties-common apt-transport-https wget"



datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check

if [ "$1" == "-c" ] ; then
	if  [ -f /usr/bin/code ]   ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	_install ${devpkgs}	
	
	_insatallvscode(){
		echo "マイクロソフトのpgpkeyを取得します"
		curl -sSL https://packages.microsoft.com/keys/microsoft.asc -o microsoft.asc
		sudo apt-key add microsoft.asc
		
		echo "マイクロソフトのリポジトリを追加します。"
		echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"  | sudo tee /etc/apt/sources.list.d/vscode.list
		sudo apt update
	}	

	_insatallvscode	
	
	if 	_install ${aptpkgs}	  ; then
		_log "$debpkgsインストールに成功しました。"
	else
		sudo apt update --fix-missing
		if sudo apt install --fix-broken ; then
			_log "$debpkgsインストールに成功しました。"
		else
			_err "$debpkgsのインストールに失敗しました。"

		fi

	fi

	
# Purge
elif [ "$1" == "-p" ] ; then

	_purge ${aptpkgs}
	sudo rm -f /etc/apt/sources.list.d/vscode.list

fi


